spring:
  application:
    name: aps8
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/aps8
    username: postgres
    password: postgres

application:
  input-test-data: false
  default-password: admin
  security:
    jwt:
      secret-key: lTua10BsvzyG53ArO6rKQhT4SRi0suMIpQ2MDRHnFq6eaOa2P29c031lw78wCLr
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days